image: generic-c

stages:
  - test

test:
  stage: test
  script:
    - dnf -y install python3
    - dnf -y install python3-pip
    - pip3 install xmlrunner
    - python3 test.py
  artifacts:
    when: always
    paths:
      - report.xml